package metier;
// Generated 25-sept.-2019 16:10:06 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Deplacement generated by hbm2java
 */
public class Deplacement implements java.io.Serializable {

    private int idDep;
    private Lieu lieuByIdlieuArr;
    private Lieu lieuByIdlieuDep;
    private BigDecimal prix;
    private Date dateHeureDepart;
    private Date dateHeureArrive;
    private String codeVol;
    private String codeNav;
    private Set infoses = new HashSet(0);

    public Deplacement() {
    }

    public Deplacement(int idDep, Lieu lieuByIdlieuArr, Lieu lieuByIdlieuDep) {
        this.idDep = idDep;
        this.lieuByIdlieuArr = lieuByIdlieuArr;
        this.lieuByIdlieuDep = lieuByIdlieuDep;
    }

    public Deplacement(int idDep, Lieu lieuByIdlieuArr, Lieu lieuByIdlieuDep, BigDecimal prix, Date dateHeureDepart, Date dateHeureArrive, String codeVol, String codeNav, Set infoses) {
        this.idDep = idDep;
        this.lieuByIdlieuArr = lieuByIdlieuArr;
        this.lieuByIdlieuDep = lieuByIdlieuDep;
        this.prix = prix;
        this.dateHeureDepart = dateHeureDepart;
        this.dateHeureArrive = dateHeureArrive;
        this.codeVol = codeVol;
        this.codeNav = codeNav;
        this.infoses = infoses;
    }

    public Deplacement(Lieu lieuByIdlieuArr, Lieu lieuByIdlieuDep, BigDecimal prix, Date dateHeureDepart, Date dateHeureArrive, String codeVol, String codeNav) {
        this.lieuByIdlieuArr = lieuByIdlieuArr;
        this.lieuByIdlieuDep = lieuByIdlieuDep;
        this.prix = prix;
        this.dateHeureDepart = dateHeureDepart;
        this.dateHeureArrive = dateHeureArrive;
        this.codeVol = codeVol;
        this.codeNav = codeNav;
    }

    public int getIdDep() {
        return this.idDep;
    }

    public void setIdDep(int idDep) {
        this.idDep = idDep;
    }

    public Lieu getLieuByIdlieuArr() {
        return this.lieuByIdlieuArr;
    }

    public void setLieuByIdlieuArr(Lieu lieuByIdlieuArr) {
        this.lieuByIdlieuArr = lieuByIdlieuArr;
    }

    public Lieu getLieuByIdlieuDep() {
        return this.lieuByIdlieuDep;
    }

    public void setLieuByIdlieuDep(Lieu lieuByIdlieuDep) {
        this.lieuByIdlieuDep = lieuByIdlieuDep;
    }

    public BigDecimal getPrix() {
        return this.prix;
    }

    public void setPrix(BigDecimal prix) {
        this.prix = prix;
    }

    public Date getDateHeureDepart() {
        return this.dateHeureDepart;
    }

    public void setDateHeureDepart(Date dateHeureDepart) {
        this.dateHeureDepart = dateHeureDepart;
    }

    public Date getDateHeureArrive() {
        return this.dateHeureArrive;
    }

    public void setDateHeureArrive(Date dateHeureArrive) {
        this.dateHeureArrive = dateHeureArrive;
    }

    public String getCodeVol() {
        return this.codeVol;
    }

    public void setCodeVol(String codeVol) {
        this.codeVol = codeVol;
    }

    public String getCodeNav() {
        return this.codeNav;
    }

    public void setCodeNav(String codeNav) {
        this.codeNav = codeNav;
    }

    public Set getInfoses() {
        return this.infoses;
    }

    public void setInfoses(Set infoses) {
        this.infoses = infoses;
    }

}
