package metier;
// Generated 25-sept.-2019 16:10:06 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Lieu generated by hbm2java
 */
public class Lieu implements java.io.Serializable {

    private int idlieu;
    private String codeAero;
    private String codePort;
    private String nom;
    private String ville;
    private String pays;
    private Set deplacementsForIdlieuArr = new HashSet(0);
    private Set deplacementsForIdlieuDep = new HashSet(0);

    public Lieu() {
    }

    public Lieu(int idlieu) {
        this.idlieu = idlieu;
    }

    public Lieu(int idlieu, String codeAero, String codePort, String nom, String ville, String pays, Set deplacementsForIdlieuArr, Set deplacementsForIdlieuDep) {
        this.idlieu = idlieu;
        this.codeAero = codeAero;
        this.codePort = codePort;
        this.nom = nom;
        this.ville = ville;
        this.pays = pays;
        this.deplacementsForIdlieuArr = deplacementsForIdlieuArr;
        this.deplacementsForIdlieuDep = deplacementsForIdlieuDep;
    }

    public Lieu(String codeAero, String codePort, String nom, String ville, String pays) {
        this.codeAero = codeAero;
        this.codePort = codePort;
        this.nom = nom;
        this.ville = ville;
        this.pays = pays;  
    }

    public int getIdlieu() {
        return this.idlieu;
    }

    public void setIdlieu(int idlieu) {
        this.idlieu = idlieu;
    }

    public String getCodeAero() {
        return this.codeAero;
    }

    public void setCodeAero(String codeAero) {
        this.codeAero = codeAero;
    }

    public String getCodePort() {
        return this.codePort;
    }

    public void setCodePort(String codePort) {
        this.codePort = codePort;
    }

    public String getNom() {
        return this.nom;
    }

    public void setNom(String nom) {
        this.nom = nom;
    }

    public String getVille() {
        return this.ville;
    }

    public void setVille(String ville) {
        this.ville = ville;
    }

    public String getPays() {
        return this.pays;
    }

    public void setPays(String pays) {
        this.pays = pays;
    }

    public Set getDeplacementsForIdlieuArr() {
        return this.deplacementsForIdlieuArr;
    }

    public void setDeplacementsForIdlieuArr(Set deplacementsForIdlieuArr) {
        this.deplacementsForIdlieuArr = deplacementsForIdlieuArr;
    }

    public Set getDeplacementsForIdlieuDep() {
        return this.deplacementsForIdlieuDep;
    }

    public void setDeplacementsForIdlieuDep(Set deplacementsForIdlieuDep) {
        this.deplacementsForIdlieuDep = deplacementsForIdlieuDep;
    }

}
