package metier;
// Generated 25-sept.-2019 16:10:06 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Voyage generated by hbm2java
 */
public class Voyage  implements java.io.Serializable {


     private int idVoyage;
     private String codeVoyage;
     private String nom;
     private String description;
     private Set infoses = new HashSet(0);

    public Voyage() {
    }

	
    public Voyage(int idVoyage) {
        this.idVoyage = idVoyage;
    }
    public Voyage(int idVoyage, String codeVoyage, String nom, String description, Set infoses) {
       this.idVoyage = idVoyage;
       this.codeVoyage = codeVoyage;
       this.nom = nom;
       this.description = description;
       this.infoses = infoses;
    }
   
    public int getIdVoyage() {
        return this.idVoyage;
    }
    
    public void setIdVoyage(int idVoyage) {
        this.idVoyage = idVoyage;
    }
    public String getCodeVoyage() {
        return this.codeVoyage;
    }
    
    public void setCodeVoyage(String codeVoyage) {
        this.codeVoyage = codeVoyage;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set getInfoses() {
        return this.infoses;
    }
    
    public void setInfoses(Set infoses) {
        this.infoses = infoses;
    }
}


